//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public string A_USERNAME { get; set; }
        public string A_PASSWORD { get; set; }
        public string A_EMAIL { get; set; }
        public string A_DISPLAYNAME { get; set; }
        public string A_GENDER { get; set; }
        public System.DateTime A_BDAY { get; set; }
        public string A_ADDRESS { get; set; }
        public string A_PHONE { get; set; }

        public bool IsLogin { get; set; }
    }
}
