//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaManagement.Model
{
    using SpaManagement.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING:BaseViewModel
    {
        public int BK_ID { get; set; }
        public string BK_MA { get; set; }

        private int _C_ID;
        public int C_ID 
        {
            get => _C_ID;
            set
            {
                _C_ID = value;
                OnPropertyChanged();
            }
        }

        private int _E_ID;
        public int E_ID 
        {
            get => _E_ID;
            set
            {
                _E_ID = value;
                OnPropertyChanged();
            } 
        }

        private int _S_ID;
        public int S_ID 
        {
            get => _S_ID;
            set
            {
                _S_ID = value;
                OnPropertyChanged();
            } 
        }

        private System.DateTime _START_TIME;
        public System.DateTime START_TIME 
        {
            get => _START_TIME;
            set
            {
                _START_TIME = value;
                OnPropertyChanged();
            }
        }

        private System.DateTime _END_TIME;
        public System.DateTime END_TIME 
        {
            get => _END_TIME;
            set
            {
                _END_TIME = value;
                OnPropertyChanged();
            }
        }
        public Nullable<bool> IS_EDITED { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual SERVICESS SERVICESS { get; set; }
    }
}
