//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaManagement.Model
{
    using SpaManagement.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPT_DETAIL:BaseViewModel
    {
        public int REC_ID { get; set; }
        public int P_ID { get; set; }

        private int _QUANTITY;
        public int QUANTITY
        {
            get => _QUANTITY;
            set
            {
                _QUANTITY = value;
                OnPropertyChanged();
            }
        }
        private decimal _PRICE;
        public decimal PRICE
        {
            get => _PRICE;
            set
            {
                _PRICE = value;
                OnPropertyChanged();
            }
        }

        private decimal _AMOUNT;
        public decimal AMOUNT
        {
            get => PRICE * QUANTITY;
            set
            {
                _AMOUNT = value;
                OnPropertyChanged();
            }
        }

        public virtual PRODUCT PRODUCT { get; set; }
        public virtual RECEIPT RECEIPT { get; set; }
    }
}
