CREATE DATABASE QUANLYSPA
GO


USE QUANLYSPA
GO

CREATE TABLE EMPLOYEE
(
	EMP_ID INT IDENTITY(1,1) PRIMARY KEY,
	EMP_MA AS CAST('NV' + RIGHT('000' + CAST(EMP_ID AS VARCHAR(3)), 3) AS CHAR(6)) PERSISTED,
	EMP_DISPLAYNAME NVARCHAR(MAX) NOT NULL,
	EMP_ADDRESS NVARCHAR(MAX),
	EMP_PHONE NVARCHAR(20),
	EMP_CCCD NVARCHAR(12),
	EMP_SALARY MONEY,
	EMP_ROLE NVARCHAR(50)
)
GO

CREATE TABLE CUSTOMER
(
	CUS_ID INT IDENTITY(1,1) PRIMARY KEY,
	CUS_MA AS CAST('KH' + RIGHT('000' + CAST(CUS_ID AS VARCHAR(3)), 3) AS CHAR(6)) PERSISTED,
	CUS_NAME NVARCHAR(MAX) NOT NULL,
	CUS_PHONE NVARCHAR(20) NOT NULL,
	CUS_EMAIL NVARCHAR(200),
	CUS_SEX NVARCHAR(5) NOT NULL
)
GO

CREATE TABLE PRODUCT
(
	PRO_ID INT IDENTITY(1,1) PRIMARY KEY,
	PRO_MA AS CAST('MP' + RIGHT('000' + CAST(PRO_ID AS VARCHAR(3)), 3) AS CHAR(6)) PERSISTED,
	PRO_NAME NVARCHAR(MAX) NOT NULL,
	PRICE MONEY NOT NULL,
)
GO

CREATE TABLE SERVICESS
(
	SER_ID INT IDENTITY(1,1) PRIMARY KEY,
	SER_MA AS CAST('DV' + RIGHT('000' + CAST(SER_ID AS VARCHAR(3)), 3) AS CHAR(6)) PERSISTED,
	SER_NAME NVARCHAR(MAX) NOT NULL,
	PRICE MONEY NOT NULL
)
GO

CREATE TABLE BOOKING 
(
	BK_ID INT IDENTITY(1,1) PRIMARY KEY,
	BK_MA AS CAST('BK' + RIGHT('000' + CAST(BK_ID AS VARCHAR(3)), 3) AS CHAR(6)) PERSISTED,
	C_ID INT NOT NULL,
	E_ID INT NOT NULL,
	S_ID INT NOT NULL,
	START_TIME DATETIME NOT NULL,
	END_TIME DATETIME NOT NULL,
	FOREIGN KEY (E_ID) REFERENCES EMPLOYEE(EMP_ID),
	FOREIGN KEY (S_ID) REFERENCES SERVICESS(SER_ID),
	FOREIGN KEY (C_ID) REFERENCES CUSTOMER(CUS_ID)
)
GO

CREATE TABLE PAYMENT
(
	PMT_ID INT IDENTITY(1,1) PRIMARY KEY,
	PMT_MA AS CAST('PMT' + RIGHT('000' + CAST(PMT_ID AS VARCHAR(3)), 3) AS CHAR(6)) PERSISTED,
	C_ID INT,
	PRICE MONEY NOT NULL,
	DAYTIME DATETIME NOT NULL,
	FOREIGN KEY (C_ID) REFERENCES CUSTOMER(CUS_ID) 
)
GO

CREATE TABLE PAYMENT_DETAIL_SERVICE
(
	PMT_ID INT NOT NULL,
	S_ID INT NOT NULL,
	E_ID INT,
	PRIMARY KEY (PMT_ID, S_ID),
	FOREIGN KEY (E_ID) REFERENCES EMPLOYEE (EMP_ID),
	FOREIGN KEY (PMT_ID) REFERENCES PAYMENT (PMT_ID),
	FOREIGN KEY (S_ID) REFERENCES SERVICESS (SER_ID)
)
GO

CREATE TABLE PAYMENT_DETAIL_PRODUCT(
	PMT_ID INT NOT NULL,
	P_ID INT NOT NULL,
	QUANTITY INT NOT NULL,
	PRIMARY KEY (PMT_ID, P_ID),
	FOREIGN KEY (PMT_ID) REFERENCES PAYMENT(PMT_ID),
	FOREIGN KEY (P_ID) REFERENCES PRODUCT(PRO_ID)

)
GO

CREATE TABLE ACCOUNT(
	A_USERNAME NVARCHAR(255) PRIMARY KEY,
	A_PASSWORD NVARCHAR(255),
	A_EMAIL NVARCHAR(255)
)
GO

INSERT INTO ACCOUNT(A_USERNAME, A_PASSWORD, A_EMAIL) VALUES (N'admin', N'db69fc039dcbd2962cb4d28f5891aae1',N'phanchauhoang2004@gmail.com')
GO